# Generated by Django 5.0.7 on 2025-02-07 17:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("collection", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Journal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Creation date"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Last update date"
                    ),
                ),
                (
                    "scielo_issn",
                    models.CharField(max_length=9, verbose_name="SciELO ISSN"),
                ),
                (
                    "issns",
                    models.JSONField(
                        blank=True, default=dict, null=True, verbose_name="ISSNs"
                    ),
                ),
                (
                    "acronym",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=32,
                        null=True,
                        verbose_name="Journal Acronym",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=255, verbose_name="Journal Title"),
                ),
                (
                    "publisher_name",
                    models.JSONField(
                        blank=True,
                        default=list,
                        null=True,
                        verbose_name="Publisher Name",
                    ),
                ),
                (
                    "subject_areas",
                    models.JSONField(
                        default=list, verbose_name="Subject Areas (CAPES)"
                    ),
                ),
                (
                    "wos_subject_areas",
                    models.JSONField(default=list, verbose_name="Subject Areas (WoS)"),
                ),
                (
                    "collection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="collection.collection",
                        verbose_name="Collection",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_creator",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creator",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_last_mod_user",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updater",
                    ),
                ),
            ],
            options={
                "verbose_name": "Journal",
                "verbose_name_plural": "Journals",
                "unique_together": {("collection", "scielo_issn", "acronym")},
            },
        ),
    ]
