# Generated by Django 5.0.7 on 2025-06-12 17:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("journal", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="journal",
            name="scielo_issn",
            field=models.CharField(
                db_index=True, max_length=9, verbose_name="SciELO ISSN"
            ),
        ),
    ]
