from django.utils.translation import gettext_lazy as _


LOG_FILE_STATUS_CREATED = 'CRE'
LOG_FILE_STATUS_QUEUED = 'QUE'
LOG_FILE_STATUS_PARSING = 'PAR'
LOG_FILE_STATUS_PROCESSED = 'PRO'
LOG_FILE_STATUS_INVALIDATED = 'INV'

LOG_FILE_STATUS = [
    (LOG_FILE_STATUS_CREATED, _("Created")),
    (LOG_FILE_STATUS_QUEUED, _("Queued")),
    (LOG_FILE_STATUS_PARSING, _("Parsing")),
    (LOG_FILE_STATUS_PROCESSED, _("Processed")),
    (LOG_FILE_STATUS_INVALIDATED, _("Invalidated")),
]


COLLECTION_LOG_FILE_DATE_COUNT_OK = 'OK'
COLLECTION_LOG_FILE_DATE_COUNT_MISSING_FILES = 'MIS'
COLLECTION_LOG_FILE_DATE_COUNT_EXTRA_FILES = 'EXT'

COLLECTION_LOG_FILE_DATE_COUNT = [
    (COLLECTION_LOG_FILE_DATE_COUNT_OK, _("OK")),
    (COLLECTION_LOG_FILE_DATE_COUNT_MISSING_FILES, _("Missing Files")),
    (COLLECTION_LOG_FILE_DATE_COUNT_EXTRA_FILES, _("Extra files")),
]
