class LogFileAlreadyExistsError(Exception):
    ...

class InvalidDateFormatError(Exception):
    ...

class InvalidTemporaReferenceError(Exception):
    ...

class UndefinedApplicationConfigError(Exception):
    ...

class UndefinedCollectionConfigError(Exception):
    ...
