# Generated by Django 5.0.7 on 2025-02-07 17:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("log_manager", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="collectionconfig",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="collectionconfig",
            name="collection",
        ),
        migrations.RemoveField(
            model_name="collectionconfig",
            name="creator",
        ),
        migrations.RemoveField(
            model_name="collectionconfig",
            name="updated_by",
        ),
        migrations.AlterUniqueTogether(
            name="logprocessedrow",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="logprocessedrow",
            name="creator",
        ),
        migrations.RemoveField(
            model_name="logprocessedrow",
            name="log_file",
        ),
        migrations.RemoveField(
            model_name="logprocessedrow",
            name="updated_by",
        ),
        migrations.DeleteModel(
            name="ApplicationConfig",
        ),
        migrations.DeleteModel(
            name="CollectionConfig",
        ),
        migrations.DeleteModel(
            name="LogProcessedRow",
        ),
    ]
