# Generated by Django 5.0.7 on 2025-05-18 15:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("log_manager", "0002_alter_collectionconfig_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="collectionlogfiledatecount",
            name="is_usage_metric_computed",
            field=models.BooleanField(
                default=False, verbose_name="Is Usage Metric Computed"
            ),
        ),
    ]
