# Generated by Django 5.0.7 on 2025-05-24 15:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("log_manager", "0003_collectionlogfiledatecount_is_usage_metric_computed"),
    ]

    operations = [
        migrations.AddField(
            model_name="logfile",
            name="validation",
            field=models.JSONField(
                blank=True, default=dict, null=True, verbose_name="Validation"
            ),
        ),
    ]
