# Generated by Django 5.0.7 on 2025-06-12 17:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("log_manager", "0004_logfile_validation"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="logfile",
            name="status",
            field=models.CharField(
                choices=[
                    ("CRE", "Created"),
                    ("QUE", "Queued"),
                    ("PAR", "Parsing"),
                    ("PRO", "Processed"),
                    ("INV", "Invalidated"),
                    ("IGN", "Ignored"),
                ],
                max_length=3,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="logfiledate",
            name="date",
            field=models.DateField(db_index=True, verbose_name="Date"),
        ),
        migrations.AddIndex(
            model_name="logfiledate",
            index=models.Index(
                fields=["date", "log_file"], name="log_manager_date_32b410_idx"
            ),
        ),
    ]
