# Generated by Django 5.0.7 on 2025-06-22 15:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("log_manager", "0005_alter_logfile_status_alter_logfiledate_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="logfile",
            name="last_processed_line",
            field=models.IntegerField(
                blank=True, default=0, verbose_name="Last Processed Line"
            ),
        ),
    ]
