# Generated by Django 5.0.7 on 2025-06-22 17:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("log_manager", "0006_logfile_last_processed_line"),
    ]

    operations = [
        migrations.AddField(
            model_name="logfile",
            name="summary",
            field=models.JSONField(
                blank=True, default=dict, null=True, verbose_name="Summary"
            ),
        ),
    ]
