# Generated by Django 5.0.7 on 2025-08-06 19:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("log_manager", "0007_logfile_summary"),
    ]

    operations = [
        migrations.AlterField(
            model_name="logfile",
            name="status",
            field=models.CharField(
                choices=[
                    ("CRE", "Created"),
                    ("QUE", "Queued"),
                    ("PAR", "Parsing"),
                    ("PRO", "Processed"),
                    ("ERR", "Error"),
                    ("INV", "Invalidated"),
                    ("IGN", "Ignored"),
                ],
                max_length=3,
                verbose_name="Status",
            ),
        ),
    ]
