# Generated by Django 5.0.7 on 2025-08-07 00:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("log_manager", "0008_alter_logfile_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="collectionlogfiledatecount",
            name="exported_files_count",
            field=models.SmallIntegerField(
                default=0, verbose_name="Exported Files Count"
            ),
        ),
    ]
