version: '3'

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    image: scielo_usage_production_django
    platform: linux/x86_64
    depends_on:
      - redis
      - postgres
      - mailhog
      - solr
      - pgbouncer
    links:
      - pgbouncer
      - solr
      volumes:
      - .:/app:z
      - ../scms_data/scielo_usage/data/logs:/data/logs
      - ../scms_data/scielo_usage/data/supplies:/data/supplies
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.postgres
    command: /start

  pgbouncer:
    image: edoburu/pgbouncer:1.14.0
    restart: always
    environment:
      - DATABASE_URL=postgres://GVRFlLmcCNfGLhsFvSnCioYOPJPYpyfj:DAkWfpsnPHcAxMeQk2QmPOIZuz4BXG5qGFWi2hCCQE6kvndJHTuzz8SjnxOJY5qj@postgres/scielo_usage
      - MAX_CLIENT_CONN=100
    ports:
      - 6434:5432
    depends_on:
      - postgres
    links:
      - postgres
  
  solr:
      image: solr:9.3
      restart: always
      ports:
         - "8983:8983"
      volumes:
          - ./index/data:/var/solr
      environment:
          - SOLR_JAVA_MEM=-Xms512m -Xmx512m
          - SOLR_HEAP=512m

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: scielo_usage_production_postgres
    volumes:
      - ../scms_data/scielo_usage/postgresql:/var/lib/postgresql/data:Z
      - ../scms_data/scielo_usage/postgresql_backup:/backups:z
    ports:
      - "5432:5432"
    env_file:
      - ./.envs/.production/.postgres

  adminer:
    image: adminer
    container_name: scielo_usage_production_adminer
    ports:
      - "8089:8080"

  mailhog:
    image: mailhog/mailhog:v1.0.0
    container_name: scielo_usage_production_mailhog
    ports:
      - "8029:8025"

  redis:
    image: redis:6
    ports:
      - "6379:6379"

  celeryworker:
    <<: *django
    image: scielo_usage_production_celeryworker
    depends_on:
      - redis
      - postgres
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: scielo_usage_production_celerybeat
    depends_on:
      - redis
      - postgres
    command: /start-celerybeat

  flower:
    <<: *django
    image: scielo_usage_production_flower
    command: /start-flower

  traefik:
    build:
      context: .
      dockerfile: ./compose/production/traefik/Dockerfile
    image: scielo_usage_production_traefik
    depends_on:
      - django
    volumes:
      - ../scms_data/scielo_usage/traefik:/etc/traefik/acme:z
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"
      - "0.0.0.0:5555:5555"
