# Generated by Django 5.0.7 on 2025-02-09 03:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("collection", "0001_initial"),
        ("log_manager_config", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="collectionemail",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="collectionlogdirectory",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="collectionlogfilesperday",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="collectionlogdirectory",
            name="directory_name",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Directory Name"
            ),
        ),
        migrations.AlterField(
            model_name="collectionlogdirectory",
            name="path",
            field=models.CharField(max_length=255, verbose_name="Path"),
        ),
        migrations.AddConstraint(
            model_name="collectionemail",
            constraint=models.UniqueConstraint(
                fields=("collection", "email"), name="unique_collection_email"
            ),
        ),
        migrations.AddConstraint(
            model_name="collectionlogdirectory",
            constraint=models.UniqueConstraint(
                fields=("collection", "path"), name="unique_collection_path"
            ),
        ),
        migrations.AddConstraint(
            model_name="collectionlogfilesperday",
            constraint=models.UniqueConstraint(
                fields=("collection", "start_date"), name="unique_collection_start_date"
            ),
        ),
    ]
