# Generated by Django 5.0.7 on 2025-03-27 20:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("collection", "0001_initial"),
        ("log_manager_config", "0002_alter_collectionemail_unique_together_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="collectionemail",
            options={
                "verbose_name": "Collection Email",
                "verbose_name_plural": "Collection Emails",
            },
        ),
        migrations.AlterModelOptions(
            name="collectionlogdirectory",
            options={
                "verbose_name": "Collection Log Directory",
                "verbose_name_plural": "Collection Log Directories",
            },
        ),
        migrations.AlterModelOptions(
            name="collectionlogfilesperday",
            options={
                "verbose_name": "Collection Log Files Per Day",
                "verbose_name_plural": "Collection Log Files Per Day",
            },
        ),
        migrations.AlterModelOptions(
            name="supportedlogfile",
            options={
                "verbose_name": "Supported Log File",
                "verbose_name_plural": "Supported Log Files",
            },
        ),
        migrations.CreateModel(
            name="CollectionURLTranslatorClass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Creation date"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Last update date"
                    ),
                ),
                (
                    "translator_class",
                    models.CharField(
                        default="URLTranslatorClassicSite",
                        verbose_name="URL Translator Class",
                    ),
                ),
                (
                    "collection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="collection.collection",
                        verbose_name="Collection",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_creator",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creator",
                    ),
                ),
                (
                    "directory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="log_manager_config.collectionlogdirectory",
                        verbose_name="Directory",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_last_mod_user",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updater",
                    ),
                ),
            ],
            options={
                "verbose_name": "Collection URL Translator Class",
                "verbose_name_plural": "Collection URL Translator Classes",
            },
        ),
        migrations.CreateModel(
            name="CollectionValidationParameters",
            fields=[
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Creation date"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Last update date"
                    ),
                ),
                (
                    "collection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        primary_key=True,
                        serialize=False,
                        to="collection.collection",
                        verbose_name="Collection",
                    ),
                ),
                (
                    "sample_size",
                    models.FloatField(default=0.1, verbose_name="Sample Size"),
                ),
                (
                    "buffer_size",
                    models.IntegerField(default=2048, verbose_name="Buffer Size"),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_creator",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creator",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_last_mod_user",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updater",
                    ),
                ),
            ],
            options={
                "verbose_name": "Collection Validation Parameters",
                "verbose_name_plural": "Collection Validation Parameters",
            },
        ),
        migrations.AddConstraint(
            model_name="collectionurltranslatorclass",
            constraint=models.UniqueConstraint(
                fields=("collection", "directory"), name="unique_collection_directory"
            ),
        ),
    ]
