# Generated by Django 5.2.12 on 2026-09-11 01:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("log_manager_config", "0005_alter_collectionlogdirectory_translator_class"),
    ]

    operations = [
        migrations.AddField(
            model_name="logmanagercollectionconfig",
            name="opensearch_primary_shards",
            field=models.PositiveSmallIntegerField(
                default=1,
                help_text="Applied only when a new physical index is created.",
                verbose_name="OpenSearch Primary Shards",
            ),
        ),
        migrations.AddField(
            model_name="logmanagercollectionconfig",
            name="opensearch_partition_strategy",
            field=models.CharField(
                choices=[
                    ("rollover", "Continuous with size rollover"),
                    ("yearly", "One physical index per year"),
                ],
                default="rollover",
                help_text=(
                    "Uses yearly physical indexes or continuous indexes "
                    "rolled over by size."
                ),
                max_length=16,
                verbose_name="OpenSearch Partition Strategy",
            ),
        ),
    ]
