# Generated by Django 5.0.7 on 2025-02-07 17:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("collection", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Creation date"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Last update date"
                    ),
                ),
                (
                    "scielo_issn",
                    models.CharField(
                        db_index=True, max_length=9, verbose_name="SciELO ISSN"
                    ),
                ),
                (
                    "pid_v2",
                    models.CharField(
                        db_index=True, max_length=23, verbose_name="PID V2"
                    ),
                ),
                (
                    "pid_v3",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=23,
                        null=True,
                        verbose_name="PID V3",
                    ),
                ),
                (
                    "pdfs",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        null=True,
                        verbose_name="Format with Language",
                    ),
                ),
                (
                    "default_lang",
                    models.CharField(max_length=2, verbose_name="Default Language"),
                ),
                (
                    "text_langs",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        null=True,
                        verbose_name="Text Languages",
                    ),
                ),
                (
                    "processing_date",
                    models.CharField(max_length=32, verbose_name="Processing Date"),
                ),
                (
                    "publication_date",
                    models.CharField(max_length=32, verbose_name="Publication Date"),
                ),
                (
                    "publication_year",
                    models.CharField(
                        db_index=True, max_length=4, verbose_name="Publication Year"
                    ),
                ),
                (
                    "collection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="collection.collection",
                        verbose_name="Collection",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_creator",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creator",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_last_mod_user",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updater",
                    ),
                ),
            ],
            options={
                "verbose_name": "Article",
                "verbose_name_plural": "Articles",
                "unique_together": {("collection", "scielo_issn", "pid_v2", "pid_v3")},
            },
        ),
    ]
