# Generated by Django 5.0.7 on 2025-04-01 01:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("article", "0001_initial"),
        ("collection", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="files",
            field=models.JSONField(
                blank=True, default=dict, null=True, verbose_name="Files"
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="pid_generic",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=50,
                null=True,
                verbose_name="PID Generic",
            ),
        ),
        migrations.RemoveField(
            model_name="article",
            name="pdfs",
        ),
        migrations.AlterUniqueTogether(
            name="article",
            unique_together={
                ("collection", "scielo_issn", "pid_v2", "pid_v3", "pid_generic")
            },
        ),
 
    ]
