# Generated by Django 5.0.7 on 2025-06-12 17:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("article", "0002_alter_article_unique_together_article_files_and_more"),
        ("collection", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="article",
            index=models.Index(
                fields=["collection", "scielo_issn"], name="collection_scielo_issn_idx"
            ),
        ),
    ]
