import logging

from django.conf import settings
from django.core.mail import send_mail
from django.utils.translation import gettext as _

from collection.models import Collection
from core.utils import date_utils
from log_manager_config import models as lmc_models
from reports.models import MonthlyLogReport


def send_log_report_summary_emails(
    collections=None,
    from_date=None,
    until_date=None,
    days_to_go_back=None,
):
    from_date_str, until_date_str = date_utils.get_date_range_str(
        from_date,
        until_date,
        days_to_go_back,
    )
    subject = _("Usage Log Report Summary " f"({from_date_str} to {until_date_str})")

    for collection_acron in collections or Collection.acron3_list():
        try:
            collection = Collection.objects.get(acron3=collection_acron)
        except Collection.DoesNotExist:
            logging.warning("Collection not found: %s", collection_acron)
            continue

        message = _build_collection_log_report_email_message(
            collection,
            from_date_str,
            until_date_str,
        )

        if not message:
            continue

        logging.info(
            "Sending email to collection %s. Subject: %s.",
            collection.main_name,
            subject,
        )

        _send_log_report_email_to_collection(subject, message, collection_acron)


def _build_collection_log_report_email_message(
    collection,
    from_date_str,
    until_date_str,
):
    monthly_reports = _list_latest_monthly_reports(collection)
    if not monthly_reports:
        return ""

    latest_report = monthly_reports[0]
    message = _build_current_month_report_section(
        collection,
        latest_report,
        from_date_str,
        until_date_str,
    )

    if len(monthly_reports) > 1:
        previous_report = monthly_reports[1]
        message += _build_previous_month_report_section(previous_report)
        message += _build_month_over_month_report_section(
            latest_report,
            previous_report,
        )

    message += "\n---\nThis report is automatically generated by SciELO Usage.\n"
    return message


def _list_latest_monthly_reports(collection):
    return list(
        MonthlyLogReport.objects.filter(
            collection=collection,
        ).order_by(
            "-year", "-month"
        )[:2]
    )


def _build_current_month_report_section(
    collection,
    report,
    from_date_str,
    until_date_str,
):
    message = _(
        f"Usage Log Report for {collection.acron3}\n"
        f"Period: {from_date_str} to {until_date_str}\n\n"
    )
    message += _("Latest month ({latest}):\n").format(latest=report.period_label)
    message += (
        f"  Total files: {report.total_files}\n"
        f"  Validated files: {report.validated_files} ({report.pct_validated}%)\n"
        f"  Invalidated files: {report.invalidated_files}\n"
        f"  Errored files: {report.errored_files}\n"
        f"  Lines parsed: {report.lines_parsed}\n"
        f"  Valid lines: {report.valid_lines} ({report.pct_valid_lines}%)\n"
        f"  Discarded lines: {report.discarded_lines}\n"
        f"  Remote IPs: {report.ip_remote_count} ({report.pct_remote_ip}%)\n"
        f"  Local IPs: {report.ip_local_count}\n"
    )
    return message


def _build_previous_month_report_section(report):
    message = _("\nPrevious month ({prev}):\n").format(prev=report.period_label)
    message += (
        f"  Total files: {report.total_files}\n"
        f"  Validated files: {report.validated_files} ({report.pct_validated}%)\n"
        f"  Valid lines: {report.valid_lines} ({report.pct_valid_lines}%)\n"
        f"  Remote IPs: {report.ip_remote_count} ({report.pct_remote_ip}%)\n"
    )
    return message


def _build_month_over_month_report_section(latest_report, previous_report):
    if not previous_report.total_files:
        return ""

    file_diff = latest_report.total_files - previous_report.total_files
    line_diff = latest_report.lines_parsed - previous_report.lines_parsed

    message = _("\nMonth-over-month change:\n")
    message += f"  Files: {file_diff:+d}\n"
    message += f"  Lines: {line_diff:+d}\n"
    return message


def _send_log_report_email_to_collection(subject, message, collection_acron):
    emails = lmc_models.CollectionEmail.objects.filter(
        config__collection__acron3=collection_acron,
        active=True,
    ).values_list("email", flat=True)

    if not emails:
        logging.error(
            "Error. Please, add an E-mail Configuration for the collection %s.",
            collection_acron,
        )
        return

    try:
        send_mail(
            subject=subject,
            message=message,
            from_email=settings.DEFAULT_FROM_EMAIL,
            recipient_list=list(emails),
        )
    except Exception as e:
        logging.error(
            "Error sending log files report for %s: %s",
            collection_acron,
            e,
        )
