# Generated by Codex on 2026-04-27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("collection", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyMetricJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Creation date"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Last update date"
                    ),
                ),
                (
                    "access_date",
                    models.DateField(db_index=True, verbose_name="Access Date"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PEN", "Pending"),
                            ("EXP", "Exporting"),
                            ("SUC", "Exported"),
                            ("ERR", "Error"),
                        ],
                        db_index=True,
                        default="PEN",
                        max_length=3,
                        verbose_name="Status",
                    ),
                ),
                (
                    "input_log_hashes",
                    models.JSONField(default=list, verbose_name="Input Log Hashes"),
                ),
                (
                    "storage_path",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=500,
                        verbose_name="Storage Path",
                    ),
                ),
                (
                    "payload_hash",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=64,
                        verbose_name="Payload Hash",
                    ),
                ),
                (
                    "summary",
                    models.JSONField(blank=True, default=dict, verbose_name="Summary"),
                ),
                (
                    "attempts",
                    models.PositiveIntegerField(default=0, verbose_name="Attempts"),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, default="", verbose_name="Error Message"
                    ),
                ),
                (
                    "export_started_at",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="Export Started At",
                    ),
                ),
                (
                    "exported_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Exported At"
                    ),
                ),
                (
                    "collection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="collection.collection",
                        verbose_name="Collection",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_creator",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creator",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_last_mod_user",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updater",
                    ),
                ),
            ],
            options={
                "verbose_name": "Daily Metric Job",
                "verbose_name_plural": "Daily Metric Jobs",
                "unique_together": {("collection", "access_date")},
            },
        ),
        migrations.AddIndex(
            model_name="dailymetricjob",
            index=models.Index(
                fields=["collection", "access_date"],
                name="metrics_daily_coll_date_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="dailymetricjob",
            index=models.Index(
                fields=["status", "export_started_at"],
                name="metrics_daily_status_exp_idx",
            ),
        ),
    ]
