# Generated by Django 5.0.7 on 2024-08-30 00:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("wagtaildocs", "0013_delete_uploadeddocument"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Top100ArticlesFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Creation date"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Last update date"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("QUE", "Queued"),
                            ("PAR", "Parsing"),
                            ("PRO", "Processed"),
                            ("INV", "Invalidated"),
                        ],
                        default="QUE",
                        max_length=5,
                    ),
                ),
                (
                    "attachment",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtaildocs.document",
                        verbose_name="Attachment",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_creator",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creator",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_last_mod_user",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updater",
                    ),
                ),
            ],
            options={
                "verbose_name": "Top 100 Articles File",
                "verbose_name_plural": "Top 100 Articles Files",
            },
        ),
        migrations.CreateModel(
            name="Top100Articles",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Creation date"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Last update date"
                    ),
                ),
                ("pid_issn", models.CharField(max_length=9, verbose_name="PID ISSN")),
                ("year_month_day", models.DateField(verbose_name="Date of access")),
                (
                    "print_issn",
                    models.CharField(
                        blank=True, max_length=9, null=True, verbose_name="Print ISSN"
                    ),
                ),
                (
                    "online_issn",
                    models.CharField(
                        blank=True, max_length=9, null=True, verbose_name="Online ISSN"
                    ),
                ),
                (
                    "collection",
                    models.CharField(max_length=3, verbose_name="Collection Acronym 3"),
                ),
                ("pid", models.CharField(verbose_name="Publication ID")),
                (
                    "yop",
                    models.PositiveSmallIntegerField(
                        verbose_name="Year of Publication"
                    ),
                ),
                (
                    "total_item_requests",
                    models.IntegerField(verbose_name="Total Item Requests"),
                ),
                (
                    "total_item_investigations",
                    models.IntegerField(verbose_name="Total Item Investigations"),
                ),
                (
                    "unique_item_requests",
                    models.IntegerField(verbose_name="Unique Item Requests"),
                ),
                (
                    "unique_item_investigations",
                    models.IntegerField(verbose_name="Unique Item Investigations"),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_creator",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creator",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_last_mod_user",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updater",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Top 100 Articles",
                "indexes": [
                    models.Index(
                        fields=["pid_issn"], name="metrics_top_pid_iss_c1fba9_idx"
                    ),
                    models.Index(
                        fields=["year_month_day"], name="metrics_top_year_mo_8cda7b_idx"
                    ),
                ],
                "unique_together": {
                    ("collection", "pid_issn", "pid", "year_month_day")
                },
            },
        ),
    ]
