# Generated by Django 5.0.7 on 2024-08-30 17:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("metrics", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="top100articlesfile",
            name="status",
            field=models.CharField(
                choices=[
                    ("QUE", "Queued"),
                    ("PAR", "Parsing"),
                    ("PRO", "Processed"),
                    ("ERR", "Error"),
                    ("INV", "Invalidated"),
                ],
                default="QUE",
                max_length=5,
            ),
        ),
    ]
