# Generated by Django 5.0.7 on 2025-03-07 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("article", "0001_initial"),
        ("collection", "0001_initial"),
        ("journal", "0001_initial"),
        ("metrics", "0002_alter_top100articlesfile_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="top100articlesfile",
            name="attachment",
        ),
        migrations.RemoveField(
            model_name="top100articlesfile",
            name="creator",
        ),
        migrations.RemoveField(
            model_name="top100articlesfile",
            name="updated_by",
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="article.article",
                        verbose_name="Article",
                    ),
                ),
                (
                    "collection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="collection.collection",
                        verbose_name="Collection",
                    ),
                ),
                (
                    "journal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="journal.journal",
                        verbose_name="Journal",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item",
                "verbose_name_plural": "Items",
            },
        ),
        migrations.CreateModel(
            name="UserAgent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True, max_length=255, verbose_name="Name"
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        db_index=True, max_length=255, verbose_name="Version"
                    ),
                ),
            ],
            options={
                "verbose_name": "User Agent",
                "verbose_name_plural": "User Agents",
                "unique_together": {("name", "version")},
            },
        ),
        migrations.CreateModel(
            name="UserSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("datetime", models.DateTimeField(verbose_name="Datetime")),
                (
                    "user_ip",
                    models.CharField(
                        db_index=True, max_length=255, verbose_name="User IP"
                    ),
                ),
                (
                    "user_agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="metrics.useragent",
                        verbose_name="User Agent",
                    ),
                ),
            ],
            options={
                "verbose_name": "User Session",
                "verbose_name_plural": "User Sessions",
            },
        ),
        migrations.CreateModel(
            name="ItemAccess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "country_code",
                    models.CharField(
                        db_index=True, max_length=2, verbose_name="Country"
                    ),
                ),
                (
                    "media_language",
                    models.CharField(
                        db_index=True, max_length=2, verbose_name="Media Language"
                    ),
                ),
                (
                    "media_format",
                    models.CharField(max_length=10, verbose_name="Media Format"),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="metrics.item",
                        verbose_name="Item",
                    ),
                ),
                (
                    "user_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="metrics.usersession",
                        verbose_name="User Session",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item Access",
                "verbose_name_plural": "Items Access",
            },
        ),
        migrations.DeleteModel(
            name="Top100Articles",
        ),
    ]
