# Generated by Django 5.0.7 on 2025-03-07 16:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("metrics", "0003_remove_top100articlesfile_attachment_and_more"),
        ("tracker", "0003_logfilediscardedline_delete_top100articlesfileevent"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Top100ArticlesFile",
        ),
        migrations.AddIndex(
            model_name="item",
            index=models.Index(
                fields=["collection", "journal", "article"],
                name="metrics_ite_collect_6971a5_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="item",
            index=models.Index(
                fields=["collection", "journal"], name="metrics_ite_collect_b5f79b_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="item",
            unique_together={("collection", "journal", "article")},
        ),
        migrations.AlterUniqueTogether(
            name="usersession",
            unique_together={("datetime", "user_agent", "user_ip")},
        ),
        migrations.AlterUniqueTogether(
            name="itemaccess",
            unique_together={
                (
                    "item",
                    "user_session",
                    "country_code",
                    "media_format",
                    "media_language",
                )
            },
        ),
    ]
