# Generated by Django 5.0.7 on 2025-03-27 20:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("metrics", "0004_delete_top100articlesfile_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="itemaccess",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="itemaccess",
            name="click_timestamps",
            field=models.JSONField(default=dict, verbose_name="Click Timestamps"),
        ),
        migrations.AddField(
            model_name="itemaccess",
            name="content_type",
            field=models.CharField(
                default="undefined", max_length=16, verbose_name="Content Type"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="itemaccess",
            name="media_format",
            field=models.CharField(
                db_index=True, max_length=10, verbose_name="Media Format"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="itemaccess",
            unique_together={
                (
                    "item",
                    "user_session",
                    "country_code",
                    "media_format",
                    "media_language",
                    "content_type",
                )
            },
        ),
    ]
