# Generated by Django 5.0.7 on 2025-03-31 21:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("metrics", "0005_alter_itemaccess_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itemaccess",
            name="content_type",
            field=models.CharField(max_length=32, verbose_name="Content Type"),
        ),
    ]
