# Generated by Django 5.0.7 on 2025-06-12 17:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("metrics", "0006_alter_itemaccess_content_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usersession",
            name="datetime",
            field=models.DateTimeField(db_index=True, verbose_name="Datetime"),
        ),
        migrations.AddIndex(
            model_name="itemaccess",
            index=models.Index(
                fields=["item", "user_session"], name="metrics_ite_item_id_8799c9_idx"
            ),
        ),
    ]
