# Generated by Django 5.0.7 on 2025-06-22 17:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("metrics", "0007_alter_usersession_datetime_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="itemaccess",
            unique_together=None,
        ),
        migrations.AlterUniqueTogether(
            name="useragent",
            unique_together=None,
        ),
        migrations.AlterUniqueTogether(
            name="usersession",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="itemaccess",
            name="user_session",
        ),
        migrations.RemoveField(
            model_name="usersession",
            name="user_agent",
        ),
        migrations.RemoveField(
            model_name="itemaccess",
            name="item",
        ),
        migrations.DeleteModel(
            name="Item",
        ),
        migrations.DeleteModel(
            name="ItemAccess",
        ),
        migrations.DeleteModel(
            name="UserAgent",
        ),
        migrations.DeleteModel(
            name="UserSession",
        ),
    ]
