COLLECTION_ACRON3_SIZE_MAP = {
    "scl": "xlarge",
    "chl": "large",
    "col": "large",
    "mex": "large",
    "cri": "medium",
    "esp": "medium",
    "psi": "medium",
    "prt": "medium",
    "ven": "medium",
    "arg": "small",
    "bol": "small",
    "books": "small",
    "cub": "small",
    "data": "small",
    "dom": "small",
    "ecu": "small",
    "per": "small",
    "preprints": "small",
    "pry": "small",
    "rve": "small",
    "rvt": "small",
    "spa": "small",
    "sss": "small",
    "sza": "small",
    "ury": "small",
    "wid": "small",
}

COLLECTION_SIZE_SAMPLE_MAP = {
    "small": 1.0,
    "medium": 0.5,
    "large": 0.1,
    "xlarge": 0.1,
}

COLLECTION_OPAC_URL_MAP = {
    "dom": "https://scielo.do/api/v1/counter_dict",
    "scl": "https://www.scielo.br/api/v1/counter_dict",
}


def get_collection_size(collection_acronym):
    return COLLECTION_ACRON3_SIZE_MAP.get(collection_acronym, "small")


def get_collection_parse_queue(collection_acronym):
    return f"parse_{get_collection_size(collection_acronym)}"

LOG_MANAGER_SEED_DATA = [
    {
        "acronym": "arg",
        "directory_name": "Site clássico",
        "path": "/app/logs/bkp-ratchet/scielo.ar",
        "quantity": 1,
        "start_date": "2020-01-01",
        "e-mail": "tecnologia@scielo.org",
        "translator_class": "classic",
    },
    {
        "acronym": "bol",
        "directory_name": "Site clássico",
        "path": "/app/logs/bkp-ratchet/scielo.bo",
        "quantity": 1,
        "start_date": "2020-01-01",
        "e-mail": "tecnologia@scielo.org",
        "translator_class": "classic",
    },
    {
        "acronym": "chl",
        "directory_name": "Site clássico",
        "path": "/app/logs/bkp-ratchet/scielo.cl",
        "quantity": 1,
        "start_date": "2020-01-01",
        "e-mail": "tecnologia@scielo.org",
        "translator_class": "classic",
    },
    {
        "acronym": "col",
        "directory_name": "Site clássico",
        "path": "/app/logs/bkp-ratchet/scielo.co",
        "quantity": 1,
        "start_date": "2020-01-01",
        "e-mail": "tecnologia@scielo.org",
        "translator_class": "classic",
    },
    {
        "acronym": "cri",
        "directory_name": "Site clássico",
        "path": "/app/logs/bkp-ratchet/scielo.cr",
        "quantity": 1,
        "start_date": "2020-01-01",
        "e-mail": "tecnologia@scielo.org",
        "translator_class": "classic",
    },
    {
        "acronym": "cub",
        "directory_name": "Site clássico",
        "path": "/app/logs/bkp-ratchet/scielo.cu",
        "quantity": 1,
        "start_date": "2020-01-01",
        "e-mail": "tecnologia@scielo.org",
        "translator_class": "classic",
    },
    {
        "acronym": "ecu",
        "directory_name": "Site clássico",
        "path": "/app/logs/bkp-ratchet/scielo.ec",
        "quantity": 1,
        "start_date": "2020-01-01",
        "e-mail": "tecnologia@scielo.org",
        "translator_class": "classic",
    },
    {
        "acronym": "esp",
        "directory_name": "Site clássico",
        "path": "/app/logs/bkp-ratchet/scielo.es",
        "quantity": 1,
        "start_date": "2020-01-01",
        "e-mail": "tecnologia@scielo.org",
        "translator_class": "classic",
    },
    {
        "acronym": "mex",
        "directory_name": "Site clássico",
        "path": "/app/logs/bkp-ratchet/scielo.mx",
        "quantity": 1,
        "start_date": "2020-01-01",
        "e-mail": "tecnologia@scielo.org",
        "translator_class": "classic",
    },
    {
        "acronym": "per",
        "directory_name": "Site clássico",
        "path": "/app/logs/bkp-ratchet/scielo.pe",
        "quantity": 1,
        "start_date": "2020-01-01",
        "e-mail": "tecnologia@scielo.org",
        "translator_class": "classic",
    },
    {
        "acronym": "prt",
        "directory_name": "Site clássico",
        "path": "/app/logs/bkp-ratchet/scielo.pt",
        "quantity": 1,
        "start_date": "2020-01-01",
        "e-mail": "tecnologia@scielo.org",
        "translator_class": "classic",
    },
    {
        "acronym": "pry",
        "directory_name": "Site clássico",
        "path": "/app/logs/bkp-ratchet/scielo.py",
        "quantity": 1,
        "start_date": "2020-01-01",
        "e-mail": "tecnologia@scielo.org",
        "translator_class": "classic",
    },
    {
        "acronym": "psi",
        "directory_name": "Site clássico",
        "path": "/app/logs/bkp-ratchet/scielo.pepsic",
        "quantity": 1,
        "start_date": "2020-01-01",
        "e-mail": "tecnologia@scielo.org",
        "translator_class": "classic",
    },
    {
        "acronym": "rve",
        "directory_name": "Site clássico",
        "path": "/app/logs/bkp-ratchet/scielo.revenf",
        "quantity": 1,
        "start_date": "2020-01-01",
        "e-mail": "tecnologia@scielo.org",
        "translator_class": "classic",
    },
    {
        "acronym": "scl",
        "directory_name": "SciELO Brasil",
        "path": "/app/logs/bkp-bunnynet/scielo-br",
        "quantity": 2,
        "start_date": "2020-01-01",
        "e-mail": "tecnologia@scielo.org",
        "translator_class": "opac",
    },
    {
        "acronym": "scl",
        "directory_name": "SciELO Brasil 2",
        "path": "/app/logs/bkp-bunnynet/scielo-br-2",
        "quantity": 2,
        "start_date": "2020-01-01",
        "e-mail": "tecnologia@scielo.org",
        "translator_class": "opac",
    },
    {
        "acronym": "sza",
        "directory_name": "Site clássico",
        "path": "/app/logs/bkp-ratchet/scielo.za",
        "quantity": 1,
        "start_date": "2020-01-01",
        "e-mail": "tecnologia@scielo.org",
        "translator_class": "classic",
    },
    {
        "acronym": "ury",
        "directory_name": "Site clássico",
        "path": "/app/logs/bkp-ratchet/scielo.uy",
        "quantity": 1,
        "start_date": "2020-01-01",
        "e-mail": "tecnologia@scielo.org",
        "translator_class": "classic",
    },
    {
        "acronym": "ven",
        "directory_name": "Site clássico",
        "path": "/app/logs/bkp-ratchet/scielo.ve",
        "quantity": 1,
        "start_date": "2020-01-01",
        "e-mail": "tecnologia@scielo.org",
        "translator_class": "classic",
    },
    {
        "acronym": "wid",
        "directory_name": "SciELO Caribbean",
        "path": "/app/logs/bkp-bunnynet/caribbean",
        "quantity": 1,
        "start_date": "2020-01-01",
        "e-mail": "tecnologia@scielo.org",
        "translator_class": "classic",
    },
    {
        "acronym": "books",
        "directory_name": "SciELO Books",
        "path": "/app/logs/bkp-bunnynet/books",
        "quantity": 1,
        "start_date": "2012-01-01",
        "e-mail": "tecnologia@scielo.org",
        "translator_class": "books",
    },
]
