from log_manager_config.choices import OpenSearchPartitionStrategy

COLLECTION_OPAC_URL_MAP = {
    "dom": "https://scielo.do/api/v1/counter_dict",
    "scl": "https://www.scielo.br/api/v1/counter_dict",
}
LOG_MANAGER_SEED_DATA = [
    {
        "acronym": "arg",
        "directory_name": "Site clássico",
        "path": "/app/logs/bkp-ratchet/scielo.ar",
        "quantity": 1,
        "start_date": "2020-01-01",
        "e-mail": "tecnologia@scielo.org",
        "translator_class": "classic",
    },
    {
        "acronym": "bol",
        "directory_name": "Site clássico",
        "path": "/app/logs/bkp-ratchet/scielo.bo",
        "quantity": 1,
        "start_date": "2020-01-01",
        "e-mail": "tecnologia@scielo.org",
        "translator_class": "classic",
    },
    {
        "acronym": "chl",
        "opensearch_partition_strategy": OpenSearchPartitionStrategy.YEARLY,
        "directory_name": "Site clássico",
        "path": "/app/logs/bkp-ratchet/scielo.cl",
        "quantity": 1,
        "start_date": "2020-01-01",
        "e-mail": "tecnologia@scielo.org",
        "translator_class": "classic",
        "sample_size": 0.1,
    },
    {
        "acronym": "col",
        "opensearch_partition_strategy": OpenSearchPartitionStrategy.YEARLY,
        "directory_name": "Site clássico",
        "path": "/app/logs/bkp-ratchet/scielo.co",
        "quantity": 1,
        "start_date": "2020-01-01",
        "e-mail": "tecnologia@scielo.org",
        "translator_class": "classic",
        "sample_size": 0.1,
    },
    {
        "acronym": "cri",
        "directory_name": "Site clássico",
        "path": "/app/logs/bkp-ratchet/scielo.cr",
        "quantity": 1,
        "start_date": "2020-01-01",
        "e-mail": "tecnologia@scielo.org",
        "translator_class": "classic",
        "sample_size": 0.5,
    },
    {
        "acronym": "cub",
        "directory_name": "Site clássico",
        "path": "/app/logs/bkp-ratchet/scielo.cu",
        "quantity": 1,
        "start_date": "2020-01-01",
        "e-mail": "tecnologia@scielo.org",
        "translator_class": "classic",
    },
    {
        "acronym": "data",
        "directory_name": "Dataverse legado",
        "path": "/app/logs/bkp-dataverse",
        "quantity": 1,
        "start_date": "2020-01-01",
        "e-mail": "tecnologia@scielo.org",
        "translator_class": "dataverse",
        "directory_active": False,
    },
    {
        "acronym": "data",
        "directory_name": "BunnyNet Data",
        "path": "/app/logs/bkp-bunnynet/data",
        "quantity": 1,
        "start_date": "2020-01-01",
        "e-mail": "tecnologia@scielo.org",
        "translator_class": "dataverse",
    },
    {
        "acronym": "ecu",
        "directory_name": "Site clássico",
        "path": "/app/logs/bkp-ratchet/scielo.ec",
        "quantity": 1,
        "start_date": "2020-01-01",
        "e-mail": "tecnologia@scielo.org",
        "translator_class": "classic",
    },
    {
        "acronym": "esp",
        "directory_name": "Site clássico",
        "path": "/app/logs/bkp-ratchet/scielo.es",
        "quantity": 1,
        "start_date": "2020-01-01",
        "e-mail": "tecnologia@scielo.org",
        "translator_class": "classic",
        "sample_size": 0.5,
    },
    {
        "acronym": "mex",
        "opensearch_partition_strategy": OpenSearchPartitionStrategy.YEARLY,
        "directory_name": "Site clássico",
        "path": "/app/logs/bkp-ratchet/scielo.mx",
        "quantity": 1,
        "start_date": "2020-01-01",
        "e-mail": "tecnologia@scielo.org",
        "translator_class": "classic",
        "sample_size": 0.1,
    },
    {
        "acronym": "per",
        "directory_name": "Site clássico",
        "path": "/app/logs/bkp-ratchet/scielo.pe",
        "quantity": 1,
        "start_date": "2020-01-01",
        "e-mail": "tecnologia@scielo.org",
        "translator_class": "classic",
    },
    {
        "acronym": "preprints",
        "directory_name": "BunnyNet Preprints",
        "path": "/app/logs/bkp-bunnynet/preprints",
        "quantity": 1,
        "start_date": "2020-01-01",
        "e-mail": "tecnologia@scielo.org",
        "translator_class": "preprints",
    },
    {
        "acronym": "prt",
        "directory_name": "Site clássico",
        "path": "/app/logs/bkp-ratchet/scielo.pt",
        "quantity": 1,
        "start_date": "2020-01-01",
        "e-mail": "tecnologia@scielo.org",
        "translator_class": "classic",
        "sample_size": 0.5,
    },
    {
        "acronym": "pry",
        "directory_name": "Site clássico",
        "path": "/app/logs/bkp-ratchet/scielo.py",
        "quantity": 1,
        "start_date": "2020-01-01",
        "e-mail": "tecnologia@scielo.org",
        "translator_class": "classic",
    },
    {
        "acronym": "psi",
        "directory_name": "Site clássico",
        "path": "/app/logs/bkp-ratchet/scielo.pepsic",
        "quantity": 1,
        "start_date": "2020-01-01",
        "e-mail": "tecnologia@scielo.org",
        "translator_class": "classic",
        "sample_size": 0.5,
    },
    {
        "acronym": "rve",
        "directory_name": "Site clássico",
        "path": "/app/logs/bkp-ratchet/scielo.revenf",
        "quantity": 1,
        "start_date": "2020-01-01",
        "e-mail": "tecnologia@scielo.org",
        "translator_class": "classic",
    },
    {
        "acronym": "scl",
        "opensearch_partition_strategy": OpenSearchPartitionStrategy.YEARLY,
        "directory_name": "SciELO Brasil",
        "path": "/app/logs/bkp-bunnynet/scielo-br",
        "quantity": 2,
        "start_date": "2020-01-01",
        "e-mail": "tecnologia@scielo.org",
        "translator_class": "opac",
        "sample_size": 0.1,
    },
    {
        "acronym": "scl",
        "opensearch_partition_strategy": OpenSearchPartitionStrategy.YEARLY,
        "directory_name": "SciELO Brasil 2",
        "path": "/app/logs/bkp-bunnynet/scielo-br-2",
        "quantity": 2,
        "start_date": "2020-01-01",
        "e-mail": "tecnologia@scielo.org",
        "translator_class": "opac",
        "sample_size": 0.1,
    },
    {
        "acronym": "sza",
        "directory_name": "Site clássico",
        "path": "/app/logs/bkp-ratchet/scielo.za",
        "quantity": 1,
        "start_date": "2020-01-01",
        "e-mail": "tecnologia@scielo.org",
        "translator_class": "classic",
    },
    {
        "acronym": "ury",
        "directory_name": "Site clássico",
        "path": "/app/logs/bkp-ratchet/scielo.uy",
        "quantity": 1,
        "start_date": "2020-01-01",
        "e-mail": "tecnologia@scielo.org",
        "translator_class": "classic",
    },
    {
        "acronym": "ven",
        "directory_name": "Venezuela legado",
        "path": "/app/logs/bkp-venezuela",
        "quantity": 1,
        "start_date": "2020-01-01",
        "e-mail": "tecnologia@scielo.org",
        "translator_class": "classic",
        "directory_active": False,
        "sample_size": 0.5,
    },
    {
        "acronym": "ven",
        "directory_name": "Ratchet Venezuela",
        "path": "/app/logs/bkp-ratchet/scielo.ve",
        "quantity": 1,
        "start_date": "2020-01-01",
        "e-mail": "tecnologia@scielo.org",
        "translator_class": "classic",
        "directory_active": False,
        "sample_size": 0.5,
    },
    {
        "acronym": "ven",
        "directory_name": "BunnyNet Venezuela",
        "path": "/app/logs/bkp-bunnynet/venezuela",
        "quantity": 1,
        "start_date": "2020-01-01",
        "e-mail": "tecnologia@scielo.org",
        "translator_class": "classic",
        "sample_size": 0.5,
    },
    {
        "acronym": "wid",
        "directory_name": "Ratchet West Indies",
        "path": "/app/logs/bkp-ratchet/scielo.wi",
        "quantity": 1,
        "start_date": "2020-01-01",
        "e-mail": "tecnologia@scielo.org",
        "translator_class": "classic",
        "directory_active": False,
    },
    {
        "acronym": "wid",
        "directory_name": "BunnyNet Caribbean legado",
        "path": "/app/logs/bkp-bunnynet/caribbean",
        "quantity": 1,
        "start_date": "2020-01-01",
        "e-mail": "tecnologia@scielo.org",
        "translator_class": "classic",
        "directory_active": False,
    },
    {
        "acronym": "wid",
        "directory_name": "BunnyNet West Indies",
        "path": "/app/logs/bkp-bunnynet/westindies",
        "quantity": 1,
        "start_date": "2020-01-01",
        "e-mail": "tecnologia@scielo.org",
        "translator_class": "classic",
    },
    {
        "acronym": "books",
        "directory_name": "SciELO Books",
        "path": "/app/logs/bkp-bunnynet/books",
        "quantity": 1,
        "start_date": "2012-01-01",
        "e-mail": "tecnologia@scielo.org",
        "translator_class": "books",
    },
]
