COLLECTION_ACRON3_SIZE_MAP = {
    "scl": "xlarge",
    "chl": "large",
    "col": "large",
    "mex": "large",
    "cri": "medium",
    "esp": "medium",
    "psi": "medium",
    "prt": "medium",
    "ven": "medium",
    "arg": "small",
    "bol": "small",
    "books": "small",
    "cub": "small",
    "data": "small",
    "dom": "small",
    "ecu": "small",
    "per": "small",
    "preprints": "small",
    "pry": "small",
    "rve": "small",
    "rvt": "small",
    "spa": "small",
    "sss": "small",
    "sza": "small",
    "ury": "small",
    "wid": "small",
}

COLLECTION_SIZE_SAMPLE_MAP = {
    "small": 1.0,
    "medium": 0.5,
    "large": 0.1,
    "xlarge": 0.1,
}


def get_collection_size(collection_acronym):
    return COLLECTION_ACRON3_SIZE_MAP.get(collection_acronym, "small")


def get_collection_parse_queue(collection_acronym):
    return f"parse_{get_collection_size(collection_acronym)}"

LOG_MANAGER_SEED_DATA = [
    {
        "acronym": "arg",
        "directory_name": "Site clássico",
        "path": "/app/logs/scielo.ar",
        "quantity": 1,
        "start_date": "2020-01-01",
        "e-mail": "tecnologia@scielo.org",
        "translator_class": "classic",
    },
    {
        "acronym": "bol",
        "directory_name": "Site clássico",
        "path": "/app/logs/scielo.bo",
        "quantity": 1,
        "start_date": "2020-01-01",
        "e-mail": "tecnologia@scielo.org",
        "translator_class": "classic",
    },
    {
        "acronym": "chl",
        "directory_name": "Site clássico",
        "path": "/app/logs/scielo.cl",
        "quantity": 1,
        "start_date": "2020-01-01",
        "e-mail": "tecnologia@scielo.org",
        "translator_class": "classic",
    },
    {
        "acronym": "col",
        "directory_name": "Site clássico",
        "path": "/app/logs/scielo.co",
        "quantity": 1,
        "start_date": "2020-01-01",
        "e-mail": "tecnologia@scielo.org",
        "translator_class": "classic",
    },
    {
        "acronym": "cri",
        "directory_name": "Site clássico",
        "path": "/app/logs/scielo.cr",
        "quantity": 1,
        "start_date": "2020-01-01",
        "e-mail": "tecnologia@scielo.org",
        "translator_class": "classic",
    },
    {
        "acronym": "cub",
        "directory_name": "Site clássico",
        "path": "/app/logs/scielo.cu",
        "quantity": 1,
        "start_date": "2020-01-01",
        "e-mail": "tecnologia@scielo.org",
        "translator_class": "classic",
    },
    {
        "acronym": "data",
        "directory_name": "Site clássico",
        "path": "/app/logs/dataverse",
        "quantity": 1,
        "start_date": "2020-01-01",
        "e-mail": "tecnologia@scielo.org",
        "translator_class": "dataverse",
    },
    {
        "acronym": "dom",
        "directory_name": "Site novo",
        "path": "/app/logs/scielo.dom",
        "quantity": 1,
        "start_date": "2026-01-01",
        "e-mail": "tecnologia@scielo.org",
        "translator_class": "opac",
    },
    {
        "acronym": "ecu",
        "directory_name": "Site clássico",
        "path": "/app/logs/scielo.ec",
        "quantity": 1,
        "start_date": "2020-01-01",
        "e-mail": "tecnologia@scielo.org",
        "translator_class": "classic",
    },
    {
        "acronym": "esp",
        "directory_name": "Site clássico",
        "path": "/app/logs/scielo.es",
        "quantity": 1,
        "start_date": "2020-01-01",
        "e-mail": "tecnologia@scielo.org",
        "translator_class": "classic",
    },
    {
        "acronym": "mex",
        "directory_name": "Site clássico",
        "path": "/app/logs/scielo.mx",
        "quantity": 1,
        "start_date": "2020-01-01",
        "e-mail": "tecnologia@scielo.org",
        "translator_class": "classic",
    },
    {
        "acronym": "per",
        "directory_name": "Site clássico",
        "path": "/app/logs/scielo.pe",
        "quantity": 1,
        "start_date": "2020-01-01",
        "e-mail": "tecnologia@scielo.org",
        "translator_class": "classic",
    },
    {
        "acronym": "preprints",
        "directory_name": "Site clássico",
        "path": "/app/logs/submission-node01",
        "quantity": 1,
        "start_date": "2020-01-01",
        "e-mail": "tecnologia@scielo.org",
        "translator_class": "preprints",
    },
    {
        "acronym": "prt",
        "directory_name": "Site clássico",
        "path": "/app/logs/scielo.pt",
        "quantity": 1,
        "start_date": "2020-01-01",
        "e-mail": "tecnologia@scielo.org",
        "translator_class": "classic",
    },
    {
        "acronym": "pry",
        "directory_name": "Site clássico",
        "path": "/app/logs/scielo.py",
        "quantity": 1,
        "start_date": "2020-01-01",
        "e-mail": "tecnologia@scielo.org",
        "translator_class": "classic",
    },
    {
        "acronym": "psi",
        "directory_name": "Site clássico",
        "path": "/app/logs/scielo.pepsic",
        "quantity": 1,
        "start_date": "2020-01-01",
        "e-mail": "tecnologia@scielo.org",
        "translator_class": "classic",
    },
    {
        "acronym": "rve",
        "directory_name": "Site clássico",
        "path": "/app/logs/scielo.revenf",
        "quantity": 1,
        "start_date": "2020-01-01",
        "e-mail": "tecnologia@scielo.org",
        "translator_class": "classic",
    },
    {
        "acronym": "rvt",
        "directory_name": "Site clássico",
        "path": "/app/logs/scielo.revtur",
        "quantity": 1,
        "start_date": "2020-01-01",
        "e-mail": "tecnologia@scielo.org",
        "translator_class": "classic",
    },
    {
        "acronym": "scl",
        "directory_name": "Site novo",
        "path": "/app/logs/scielo.br",
        "quantity": 1,
        "start_date": "2020-01-01",
        "e-mail": "tecnologia@scielo.org",
        "translator_class": "opac",
    },
    {
        "acronym": "spa",
        "directory_name": "Site novo - versão prévia",
        "path": "/app/logs/scielo.sp",
        "quantity": 2,
        "start_date": "2020-01-01",
        "e-mail": "tecnologia@scielo.org",
        "translator_class": "opac_alpha",
    },
    {
        "acronym": "sss",
        "directory_name": "Site clássico",
        "path": "/app/logs/scielo.ss",
        "quantity": 1,
        "start_date": "2020-01-01",
        "e-mail": "tecnologia@scielo.org",
        "translator_class": "classic",
    },
    {
        "acronym": "sza",
        "directory_name": "Site clássico",
        "path": "/app/logs/scielo.za",
        "quantity": 1,
        "start_date": "2020-01-01",
        "e-mail": "tecnologia@scielo.org",
        "translator_class": "classic",
    },
    {
        "acronym": "ury",
        "directory_name": "Site clássico",
        "path": "/app/logs/scielo.uy",
        "quantity": 1,
        "start_date": "2020-01-01",
        "e-mail": "tecnologia@scielo.org",
        "translator_class": "classic",
    },
    {
        "acronym": "ven",
        "directory_name": "Site clássico",
        "path": "/app/logs/scielo.ve",
        "quantity": 1,
        "start_date": "2020-01-01",
        "e-mail": "tecnologia@scielo.org",
        "translator_class": "classic",
    },
    {
        "acronym": "wid",
        "directory_name": "Site clássico",
        "path": "/app/logs/scielo.wi",
        "quantity": 2,
        "start_date": "2020-01-01",
        "e-mail": "tecnologia@scielo.org",
        "translator_class": "classic",
    },
    {
        "acronym": "books",
        "directory_name": "SciELO Books",
        "path": "/app/logs/books",
        "quantity": 1,
        "start_date": "2012-01-01",
        "e-mail": "tecnologia@scielo.org",
        "translator_class": "books",
    },
]
