#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

worker_args=(
  -A config.celery_app
  worker
  -l "${CELERY_WORKER_LOG_LEVEL:-INFO}"
  --concurrency="${CELERY_WORKER_CONCURRENCY:-1}"
  --prefetch-multiplier="${CELERY_WORKER_PREFETCH_MULTIPLIER:-1}"
  -n "${CELERY_WORKER_NAME:-worker.default@%h}"
)

if [ -n "${CELERY_WORKER_QUEUES:-}" ]; then
  worker_args+=(-Q "${CELERY_WORKER_QUEUES}")
fi

exec celery "${worker_args[@]}"
