from django.utils.translation import gettext_lazy as _

ERROR = "ERROR"
EXCEPTION = "EXCEPTION"
INFO = "INFO"
WARNING = "WARNING"

EVENT_MSG_TYPE = [
    (ERROR, _("error")),
    (WARNING, _("warning")),
    (INFO, _("info")),
    (EXCEPTION, _("exception")),
]


PROGRESS_STATUS_IGNORED = "IGNORED"
PROGRESS_STATUS_REPROC = "REPROC"
PROGRESS_STATUS_TODO = "TODO"
PROGRESS_STATUS_DOING = "DOING"
PROGRESS_STATUS_DONE = "DONE"
PROGRESS_STATUS_PENDING = "PENDING"

PROGRESS_STATUS = (
    (PROGRESS_STATUS_REPROC, _("To reprocess")),
    (PROGRESS_STATUS_TODO, _("To do")),
    (PROGRESS_STATUS_DONE, _("Done")),
    (PROGRESS_STATUS_DOING, _("Doing")),
    (PROGRESS_STATUS_PENDING, _("Pending")),
    (PROGRESS_STATUS_IGNORED, _("ignored")),
)


LOG_FILE_DISCARDED_LINE_REASON_MISSING_METADATA = 'MET'
LOG_FILE_DISCARDED_LINE_REASON_MISSING_ARTICLE = 'ART'
LOG_FILE_DISCARDED_LINE_REASON_MISSING_JOURNAL = 'JOU'
LOG_FILE_DISCARDED_LINE_REASON_URL_TRANSLATION = 'URL'
LOG_FILE_DISCARDED_LINE_REASON_DATABASE_ERROR = 'DBE'

LOG_FILE_DISCARDED_LINE_REASON = [
    (LOG_FILE_DISCARDED_LINE_REASON_MISSING_METADATA, _("Missing Metadata")),
    (LOG_FILE_DISCARDED_LINE_REASON_MISSING_ARTICLE, _("Missing Article")),
    (LOG_FILE_DISCARDED_LINE_REASON_MISSING_JOURNAL, _("Missing Journal")),
    (LOG_FILE_DISCARDED_LINE_REASON_URL_TRANSLATION, _("URL Translation")),
    (LOG_FILE_DISCARDED_LINE_REASON_DATABASE_ERROR, _("Database Error")),
]


ARTICLE_EVENT_TYPE_MULTIPLE_OBJS_RETURNED = 'MUL'
ARTICLE_EVENT_TYPE_DATA_ERROR = 'ERR'

ARTICLE_EVENT_TYPE = [
    (ARTICLE_EVENT_TYPE_MULTIPLE_OBJS_RETURNED, _("Multiple Articles Returned")),
    (ARTICLE_EVENT_TYPE_DATA_ERROR, _("Data Error")),
]
