from django.utils.translation import gettext_lazy as _

LOG_FILE_DISCARDED_LINE_REASON_MISSING_METADATA = "MET"
LOG_FILE_DISCARDED_LINE_REASON_MISSING_DOCUMENT = "DOC"
LOG_FILE_DISCARDED_LINE_REASON_MISSING_SOURCE = "SRC"
LOG_FILE_DISCARDED_LINE_REASON_URL_TRANSLATION = "URL"
LOG_FILE_DISCARDED_LINE_REASON_DATABASE_ERROR = "DBE"

LOG_FILE_DISCARDED_LINE_REASON = [
    (LOG_FILE_DISCARDED_LINE_REASON_MISSING_METADATA, _("Missing Metadata")),
    (LOG_FILE_DISCARDED_LINE_REASON_MISSING_DOCUMENT, _("Missing Document")),
    (LOG_FILE_DISCARDED_LINE_REASON_MISSING_SOURCE, _("Missing Source")),
    (LOG_FILE_DISCARDED_LINE_REASON_URL_TRANSLATION, _("URL Translation")),
    (LOG_FILE_DISCARDED_LINE_REASON_DATABASE_ERROR, _("Database Error")),
]
