class ProcEventCreateError(Exception):
    ...

class UnexpectedEventCreateError(Exception):
    ...

class EventCreateError(Exception):
    ...

class EventReportCreateError(Exception):
    ...

class EventReportSaveFileError(Exception):
    ...

class EventReportCreateError(Exception):
    ...

class EventReportDeleteEventsError(Exception):
    ...
