class UndefinedCollectionLogDirectoryError(Exception):
    ...

class UndefinedCollectionEmailError(Exception):
    ...

class UndefinedCollectionFilesPerDayError(Exception):
    ...

class UndefinedSupportedLogFile(Exception):
    ...

class MultipleFilesPerDayForTheSameDateError(Exception):
    ...
