# Generated by Django 5.0.7 on 2025-03-07 16:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("log_manager", "0002_alter_collectionconfig_unique_together_and_more"),
        ("tracker", "0002_top100articlesfileevent"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LogFileDiscardedLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Creation date"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Last update date"
                    ),
                ),
                (
                    "error_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("MET", "Missing Metadata"),
                            ("ART", "Missing Article"),
                            ("JOU", "Missing Journal"),
                        ],
                        max_length=3,
                        null=True,
                        verbose_name="Error Type",
                    ),
                ),
                ("data", models.JSONField(default=dict, verbose_name="Data")),
                (
                    "message",
                    models.TextField(blank=True, null=True, verbose_name="Message"),
                ),
                ("handled", models.BooleanField(default=False, verbose_name="Handled")),
                (
                    "creator",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_creator",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creator",
                    ),
                ),
                (
                    "log_file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="log_manager.logfile",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_last_mod_user",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updater",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.DeleteModel(
            name="Top100ArticlesFileEvent",
        ),
    ]
