# Generated by Django 5.0.7 on 2025-06-14 10:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0005_articleevent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="logfilediscardedline",
            name="error_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("MET", "Missing Metadata"),
                    ("ART", "Missing Article"),
                    ("JOU", "Missing Journal"),
                    ("URL", "URL Translation"),
                    ("DBE", "Database Error"),
                ],
                max_length=3,
                null=True,
                verbose_name="Error Type",
            ),
        ),
    ]
