# Generated by Django 5.0.7 on 2025-08-09 21:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0006_alter_logfilediscardedline_error_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="logfilediscardedline",
            name="error_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("MET", "Missing Metadata"),
                    ("ART", "Missing PIDv2 or PIDv3 or PID Generic"),
                    ("JOU", "Missing ISSN"),
                    ("URL", "URL Translation"),
                    ("DBE", "Database Error"),
                ],
                max_length=3,
                null=True,
                verbose_name="Error Type",
            ),
        ),
    ]
